apiVersion: issues.github.example.com/v1
kind: GitHubIssue
metadata:
  labels:
    app.kubernetes.io/name: githubissue-operator
    app.kubernetes.io/managed-by: kustomize
  name: githubissue-sample
spec:
  repo: "biao/demorepo"
  title: "Updated Issue Title from Kubernetes"
  body: "This issue was created by the GitHubIssue operator."
  labels:
    - bug
    - operator
  tokenSecretRef: "github-token"
